version: '3.4'


services: 
  git-forks-analysis:
    build:  
      context: . 
      #    image: hbtlabs/git-forks-analysis:2
    image: hbtlabs/git-forks-analysis:latest
    volumes:
        - .:/git-forks-analysis-src:ro
        - ./out:/out
        # mount git files for cloning in read only mode
        - $HOME/.gitconfig:/root/.gitconfig:ro
        - $HOME/.ssh:/root/.ssh2:ro
