version: '3.4'


#           // TODO(hbt) ENHANCE push img

services: 
  git-forks-analysis:
    build:  
      context: . 
    image: hbtlabs/git-forks-analysis
    volumes:
        - .:/git-forks-analysis-src:ro
        - ./out:/out
        # mount git files for cloning in read only mode
        - $HOME/.gitconfig:/root/.gitconfig:ro
      # // TODO(hbt) NEXT add script to fix /root.ssh  - https://serverfault.com/questions/253313/ssh-returns-bad-owner-or-permissions-on-ssh-config
        - $HOME/.ssh:/root/.ssh2:ro
